### PR TITLE
Update fs-extra to v1.0.0

### PR DESCRIPTION
**Pull request by RyanZim**
_This contains breaking changes._

### CODE REVIEW

**Comment by RyanZim** [comment]
@kevinbeaty ping?

**Comment by kevinbeaty** [comment]
Hey Ryan. Thanks for this.  I've been busy so have not had a chance to review the breaking changes.  Have you taken a look at fs-extra functions listed within fs-promise to see if any changes are necessary?

**Comment by RyanZim** [comment]
I don't think so, changelog is here: https://github.com/jprichardson/node-fs-extra/blob/master/CHANGELOG.md#100--2016-11-01.

**Comment by kevinbeaty** [comment]
Thanks!

**Pull request merged**
